
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npx", "quartz", "build", "--serve"]
    environment:
      - NODE_ENV=development


